//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMercadoEntities : DbContext
    {
        public dbMercadoEntities()
            : base("name=dbMercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cadproduto> Cadproduto { get; set; }
        public virtual DbSet<tipoFamiliaProduto> tipoFamiliaProduto { get; set; }
        public virtual DbSet<tipoFornecedor> tipoFornecedor { get; set; }
        public virtual DbSet<tipoMercadoria> tipoMercadoria { get; set; }
        public virtual DbSet<tipoProduto> tipoProduto { get; set; }
        public virtual DbSet<tipoSetor> tipoSetor { get; set; }
        public virtual DbSet<tipoUnidadeMedida> tipoUnidadeMedida { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<CadFornecedor> CadFornecedor { get; set; }
    }
}
