#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbMercado")]
	public partial class DBMercadoClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCadproduto(Cadproduto instance);
    partial void UpdateCadproduto(Cadproduto instance);
    partial void DeleteCadproduto(Cadproduto instance);
    partial void InserttipoFamiliaProduto(tipoFamiliaProduto instance);
    partial void UpdatetipoFamiliaProduto(tipoFamiliaProduto instance);
    partial void DeletetipoFamiliaProduto(tipoFamiliaProduto instance);
    partial void InserttipoFornecedor(tipoFornecedor instance);
    partial void UpdatetipoFornecedor(tipoFornecedor instance);
    partial void DeletetipoFornecedor(tipoFornecedor instance);
    partial void InserttipoMercadoria(tipoMercadoria instance);
    partial void UpdatetipoMercadoria(tipoMercadoria instance);
    partial void DeletetipoMercadoria(tipoMercadoria instance);
    partial void InserttipoProduto(tipoProduto instance);
    partial void UpdatetipoProduto(tipoProduto instance);
    partial void DeletetipoProduto(tipoProduto instance);
    partial void InserttipoSetor(tipoSetor instance);
    partial void UpdatetipoSetor(tipoSetor instance);
    partial void DeletetipoSetor(tipoSetor instance);
    partial void InserttipoUnidadeMedida(tipoUnidadeMedida instance);
    partial void UpdatetipoUnidadeMedida(tipoUnidadeMedida instance);
    partial void DeletetipoUnidadeMedida(tipoUnidadeMedida instance);
    #endregion
		
		public DBMercadoClassesDataContext() : 
				base(global::CamadaDados.Properties.Settings.Default.dbMercadoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBMercadoClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMercadoClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMercadoClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBMercadoClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cadproduto> Cadproduto
		{
			get
			{
				return this.GetTable<Cadproduto>();
			}
		}
		
		public System.Data.Linq.Table<tipoFamiliaProduto> tipoFamiliaProduto
		{
			get
			{
				return this.GetTable<tipoFamiliaProduto>();
			}
		}
		
		public System.Data.Linq.Table<tipoFornecedor> tipoFornecedor
		{
			get
			{
				return this.GetTable<tipoFornecedor>();
			}
		}
		
		public System.Data.Linq.Table<tipoMercadoria> tipoMercadoria
		{
			get
			{
				return this.GetTable<tipoMercadoria>();
			}
		}
		
		public System.Data.Linq.Table<tipoProduto> tipoProduto
		{
			get
			{
				return this.GetTable<tipoProduto>();
			}
		}
		
		public System.Data.Linq.Table<tipoSetor> tipoSetor
		{
			get
			{
				return this.GetTable<tipoSetor>();
			}
		}
		
		public System.Data.Linq.Table<tipoUnidadeMedida> tipoUnidadeMedida
		{
			get
			{
				return this.GetTable<tipoUnidadeMedida>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cadproduto")]
	public partial class Cadproduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _codigoBarra;
		
		private string _descricaoCompleta;
		
		private System.Nullable<int> _qtdEmbalagem;
		
		private System.Nullable<int> _ID_unidadeMedida;
		
		private System.Nullable<int> _ID_sector;
		
		private System.Nullable<decimal> _custoFinal;
		
		private System.Nullable<decimal> _custoVenda;
		
		private System.Nullable<int> _ID_familiaProduto;
		
		private string _descricaoNota;
		
		private System.Nullable<decimal> _pesoLiquido;
		
		private System.Nullable<System.DateTime> _dataCadastro;
		
		private System.Nullable<System.DateTime> _validade;
		
		private System.Nullable<decimal> _pesoBruto;
		
		private System.Nullable<int> _larguraEmbalagem;
		
		private System.Nullable<int> _alturaEmbalagem;
		
		private System.Nullable<decimal> _margemLucro;
		
		private System.Nullable<System.DateTime> _dataAlteracao;
		
		private System.Nullable<int> _ID_tipoMercadoria;
		
		private System.Nullable<bool> _aceitaMultiplicacaoPdv;
		
		private System.Nullable<int> _ID_fornecedor;
		
		private System.Nullable<int> _ID_tipoProduto;
		
		private System.Nullable<int> _diasDeVendas;
		
		private System.Nullable<bool> _pesavel;
		
		private System.Nullable<bool> _vendaControlada;
		
		private System.Nullable<bool> _vendaPdv;
		
		private EntityRef<tipoFamiliaProduto> _tipoFamiliaProduto;
		
		private EntityRef<tipoFornecedor> _tipoFornecedor;
		
		private EntityRef<tipoMercadoria> _tipoMercadoria;
		
		private EntityRef<tipoProduto> _tipoProduto;
		
		private EntityRef<tipoSetor> _tipoSetor;
		
		private EntityRef<tipoUnidadeMedida> _tipoUnidadeMedida;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodigoBarraChanging(string value);
    partial void OncodigoBarraChanged();
    partial void OndescricaoCompletaChanging(string value);
    partial void OndescricaoCompletaChanged();
    partial void OnqtdEmbalagemChanging(System.Nullable<int> value);
    partial void OnqtdEmbalagemChanged();
    partial void OnID_unidadeMedidaChanging(System.Nullable<int> value);
    partial void OnID_unidadeMedidaChanged();
    partial void OnID_sectorChanging(System.Nullable<int> value);
    partial void OnID_sectorChanged();
    partial void OncustoFinalChanging(System.Nullable<decimal> value);
    partial void OncustoFinalChanged();
    partial void OncustoVendaChanging(System.Nullable<decimal> value);
    partial void OncustoVendaChanged();
    partial void OnID_familiaProdutoChanging(System.Nullable<int> value);
    partial void OnID_familiaProdutoChanged();
    partial void OndescricaoNotaChanging(string value);
    partial void OndescricaoNotaChanged();
    partial void OnpesoLiquidoChanging(System.Nullable<decimal> value);
    partial void OnpesoLiquidoChanged();
    partial void OndataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OndataCadastroChanged();
    partial void OnvalidadeChanging(System.Nullable<System.DateTime> value);
    partial void OnvalidadeChanged();
    partial void OnpesoBrutoChanging(System.Nullable<decimal> value);
    partial void OnpesoBrutoChanged();
    partial void OnlarguraEmbalagemChanging(System.Nullable<int> value);
    partial void OnlarguraEmbalagemChanged();
    partial void OnalturaEmbalagemChanging(System.Nullable<int> value);
    partial void OnalturaEmbalagemChanged();
    partial void OnmargemLucroChanging(System.Nullable<decimal> value);
    partial void OnmargemLucroChanged();
    partial void OndataAlteracaoChanging(System.Nullable<System.DateTime> value);
    partial void OndataAlteracaoChanged();
    partial void OnID_tipoMercadoriaChanging(System.Nullable<int> value);
    partial void OnID_tipoMercadoriaChanged();
    partial void OnaceitaMultiplicacaoPdvChanging(System.Nullable<bool> value);
    partial void OnaceitaMultiplicacaoPdvChanged();
    partial void OnID_fornecedorChanging(System.Nullable<int> value);
    partial void OnID_fornecedorChanged();
    partial void OnID_tipoProdutoChanging(System.Nullable<int> value);
    partial void OnID_tipoProdutoChanged();
    partial void OndiasDeVendasChanging(System.Nullable<int> value);
    partial void OndiasDeVendasChanged();
    partial void OnpesavelChanging(System.Nullable<bool> value);
    partial void OnpesavelChanged();
    partial void OnvendaControladaChanging(System.Nullable<bool> value);
    partial void OnvendaControladaChanged();
    partial void OnvendaPdvChanging(System.Nullable<bool> value);
    partial void OnvendaPdvChanged();
    #endregion
		
		public Cadproduto()
		{
			this._tipoFamiliaProduto = default(EntityRef<tipoFamiliaProduto>);
			this._tipoFornecedor = default(EntityRef<tipoFornecedor>);
			this._tipoMercadoria = default(EntityRef<tipoMercadoria>);
			this._tipoProduto = default(EntityRef<tipoProduto>);
			this._tipoSetor = default(EntityRef<tipoSetor>);
			this._tipoUnidadeMedida = default(EntityRef<tipoUnidadeMedida>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigoBarra", DbType="VarChar(50)")]
		public string codigoBarra
		{
			get
			{
				return this._codigoBarra;
			}
			set
			{
				if ((this._codigoBarra != value))
				{
					this.OncodigoBarraChanging(value);
					this.SendPropertyChanging();
					this._codigoBarra = value;
					this.SendPropertyChanged("codigoBarra");
					this.OncodigoBarraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoCompleta", DbType="VarChar(60)")]
		public string descricaoCompleta
		{
			get
			{
				return this._descricaoCompleta;
			}
			set
			{
				if ((this._descricaoCompleta != value))
				{
					this.OndescricaoCompletaChanging(value);
					this.SendPropertyChanging();
					this._descricaoCompleta = value;
					this.SendPropertyChanged("descricaoCompleta");
					this.OndescricaoCompletaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtdEmbalagem", DbType="Int")]
		public System.Nullable<int> qtdEmbalagem
		{
			get
			{
				return this._qtdEmbalagem;
			}
			set
			{
				if ((this._qtdEmbalagem != value))
				{
					this.OnqtdEmbalagemChanging(value);
					this.SendPropertyChanging();
					this._qtdEmbalagem = value;
					this.SendPropertyChanged("qtdEmbalagem");
					this.OnqtdEmbalagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_unidadeMedida", DbType="Int")]
		public System.Nullable<int> ID_unidadeMedida
		{
			get
			{
				return this._ID_unidadeMedida;
			}
			set
			{
				if ((this._ID_unidadeMedida != value))
				{
					if (this._tipoUnidadeMedida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_unidadeMedidaChanging(value);
					this.SendPropertyChanging();
					this._ID_unidadeMedida = value;
					this.SendPropertyChanged("ID_unidadeMedida");
					this.OnID_unidadeMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_sector", DbType="Int")]
		public System.Nullable<int> ID_sector
		{
			get
			{
				return this._ID_sector;
			}
			set
			{
				if ((this._ID_sector != value))
				{
					if (this._tipoSetor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_sectorChanging(value);
					this.SendPropertyChanging();
					this._ID_sector = value;
					this.SendPropertyChanged("ID_sector");
					this.OnID_sectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custoFinal", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> custoFinal
		{
			get
			{
				return this._custoFinal;
			}
			set
			{
				if ((this._custoFinal != value))
				{
					this.OncustoFinalChanging(value);
					this.SendPropertyChanging();
					this._custoFinal = value;
					this.SendPropertyChanged("custoFinal");
					this.OncustoFinalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_custoVenda", DbType="Decimal(19,4)")]
		public System.Nullable<decimal> custoVenda
		{
			get
			{
				return this._custoVenda;
			}
			set
			{
				if ((this._custoVenda != value))
				{
					this.OncustoVendaChanging(value);
					this.SendPropertyChanging();
					this._custoVenda = value;
					this.SendPropertyChanged("custoVenda");
					this.OncustoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_familiaProduto", DbType="Int")]
		public System.Nullable<int> ID_familiaProduto
		{
			get
			{
				return this._ID_familiaProduto;
			}
			set
			{
				if ((this._ID_familiaProduto != value))
				{
					if (this._tipoFamiliaProduto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_familiaProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_familiaProduto = value;
					this.SendPropertyChanged("ID_familiaProduto");
					this.OnID_familiaProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricaoNota", DbType="VarChar(22)")]
		public string descricaoNota
		{
			get
			{
				return this._descricaoNota;
			}
			set
			{
				if ((this._descricaoNota != value))
				{
					this.OndescricaoNotaChanging(value);
					this.SendPropertyChanging();
					this._descricaoNota = value;
					this.SendPropertyChanged("descricaoNota");
					this.OndescricaoNotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoLiquido", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> pesoLiquido
		{
			get
			{
				return this._pesoLiquido;
			}
			set
			{
				if ((this._pesoLiquido != value))
				{
					this.OnpesoLiquidoChanging(value);
					this.SendPropertyChanging();
					this._pesoLiquido = value;
					this.SendPropertyChanged("pesoLiquido");
					this.OnpesoLiquidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataCadastro
		{
			get
			{
				return this._dataCadastro;
			}
			set
			{
				if ((this._dataCadastro != value))
				{
					this.OndataCadastroChanging(value);
					this.SendPropertyChanging();
					this._dataCadastro = value;
					this.SendPropertyChanged("dataCadastro");
					this.OndataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validade", DbType="Date")]
		public System.Nullable<System.DateTime> validade
		{
			get
			{
				return this._validade;
			}
			set
			{
				if ((this._validade != value))
				{
					this.OnvalidadeChanging(value);
					this.SendPropertyChanging();
					this._validade = value;
					this.SendPropertyChanged("validade");
					this.OnvalidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesoBruto", DbType="Decimal(12,3)")]
		public System.Nullable<decimal> pesoBruto
		{
			get
			{
				return this._pesoBruto;
			}
			set
			{
				if ((this._pesoBruto != value))
				{
					this.OnpesoBrutoChanging(value);
					this.SendPropertyChanging();
					this._pesoBruto = value;
					this.SendPropertyChanged("pesoBruto");
					this.OnpesoBrutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_larguraEmbalagem", DbType="Int")]
		public System.Nullable<int> larguraEmbalagem
		{
			get
			{
				return this._larguraEmbalagem;
			}
			set
			{
				if ((this._larguraEmbalagem != value))
				{
					this.OnlarguraEmbalagemChanging(value);
					this.SendPropertyChanging();
					this._larguraEmbalagem = value;
					this.SendPropertyChanged("larguraEmbalagem");
					this.OnlarguraEmbalagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alturaEmbalagem", DbType="Int")]
		public System.Nullable<int> alturaEmbalagem
		{
			get
			{
				return this._alturaEmbalagem;
			}
			set
			{
				if ((this._alturaEmbalagem != value))
				{
					this.OnalturaEmbalagemChanging(value);
					this.SendPropertyChanging();
					this._alturaEmbalagem = value;
					this.SendPropertyChanged("alturaEmbalagem");
					this.OnalturaEmbalagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_margemLucro", DbType="Decimal(11,2)")]
		public System.Nullable<decimal> margemLucro
		{
			get
			{
				return this._margemLucro;
			}
			set
			{
				if ((this._margemLucro != value))
				{
					this.OnmargemLucroChanging(value);
					this.SendPropertyChanging();
					this._margemLucro = value;
					this.SendPropertyChanged("margemLucro");
					this.OnmargemLucroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataAlteracao", DbType="DateTime")]
		public System.Nullable<System.DateTime> dataAlteracao
		{
			get
			{
				return this._dataAlteracao;
			}
			set
			{
				if ((this._dataAlteracao != value))
				{
					this.OndataAlteracaoChanging(value);
					this.SendPropertyChanging();
					this._dataAlteracao = value;
					this.SendPropertyChanged("dataAlteracao");
					this.OndataAlteracaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_tipoMercadoria", DbType="Int")]
		public System.Nullable<int> ID_tipoMercadoria
		{
			get
			{
				return this._ID_tipoMercadoria;
			}
			set
			{
				if ((this._ID_tipoMercadoria != value))
				{
					if (this._tipoMercadoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_tipoMercadoriaChanging(value);
					this.SendPropertyChanging();
					this._ID_tipoMercadoria = value;
					this.SendPropertyChanged("ID_tipoMercadoria");
					this.OnID_tipoMercadoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aceitaMultiplicacaoPdv", DbType="Bit")]
		public System.Nullable<bool> aceitaMultiplicacaoPdv
		{
			get
			{
				return this._aceitaMultiplicacaoPdv;
			}
			set
			{
				if ((this._aceitaMultiplicacaoPdv != value))
				{
					this.OnaceitaMultiplicacaoPdvChanging(value);
					this.SendPropertyChanging();
					this._aceitaMultiplicacaoPdv = value;
					this.SendPropertyChanged("aceitaMultiplicacaoPdv");
					this.OnaceitaMultiplicacaoPdvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_fornecedor", DbType="Int")]
		public System.Nullable<int> ID_fornecedor
		{
			get
			{
				return this._ID_fornecedor;
			}
			set
			{
				if ((this._ID_fornecedor != value))
				{
					if (this._tipoFornecedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_fornecedorChanging(value);
					this.SendPropertyChanging();
					this._ID_fornecedor = value;
					this.SendPropertyChanged("ID_fornecedor");
					this.OnID_fornecedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_tipoProduto", DbType="Int")]
		public System.Nullable<int> ID_tipoProduto
		{
			get
			{
				return this._ID_tipoProduto;
			}
			set
			{
				if ((this._ID_tipoProduto != value))
				{
					if (this._tipoProduto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_tipoProdutoChanging(value);
					this.SendPropertyChanging();
					this._ID_tipoProduto = value;
					this.SendPropertyChanged("ID_tipoProduto");
					this.OnID_tipoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diasDeVendas", DbType="Int")]
		public System.Nullable<int> diasDeVendas
		{
			get
			{
				return this._diasDeVendas;
			}
			set
			{
				if ((this._diasDeVendas != value))
				{
					this.OndiasDeVendasChanging(value);
					this.SendPropertyChanging();
					this._diasDeVendas = value;
					this.SendPropertyChanged("diasDeVendas");
					this.OndiasDeVendasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pesavel", DbType="Bit")]
		public System.Nullable<bool> pesavel
		{
			get
			{
				return this._pesavel;
			}
			set
			{
				if ((this._pesavel != value))
				{
					this.OnpesavelChanging(value);
					this.SendPropertyChanging();
					this._pesavel = value;
					this.SendPropertyChanged("pesavel");
					this.OnpesavelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendaControlada", DbType="Bit")]
		public System.Nullable<bool> vendaControlada
		{
			get
			{
				return this._vendaControlada;
			}
			set
			{
				if ((this._vendaControlada != value))
				{
					this.OnvendaControladaChanging(value);
					this.SendPropertyChanging();
					this._vendaControlada = value;
					this.SendPropertyChanged("vendaControlada");
					this.OnvendaControladaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendaPdv", DbType="Bit")]
		public System.Nullable<bool> vendaPdv
		{
			get
			{
				return this._vendaPdv;
			}
			set
			{
				if ((this._vendaPdv != value))
				{
					this.OnvendaPdvChanging(value);
					this.SendPropertyChanging();
					this._vendaPdv = value;
					this.SendPropertyChanged("vendaPdv");
					this.OnvendaPdvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoFamiliaProduto_Cadproduto", Storage="_tipoFamiliaProduto", ThisKey="ID_familiaProduto", OtherKey="id", IsForeignKey=true)]
		public tipoFamiliaProduto tipoFamiliaProduto
		{
			get
			{
				return this._tipoFamiliaProduto.Entity;
			}
			set
			{
				tipoFamiliaProduto previousValue = this._tipoFamiliaProduto.Entity;
				if (((previousValue != value) 
							|| (this._tipoFamiliaProduto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoFamiliaProduto.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoFamiliaProduto.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_familiaProduto = value.id;
					}
					else
					{
						this._ID_familiaProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoFamiliaProduto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoFornecedor_Cadproduto", Storage="_tipoFornecedor", ThisKey="ID_fornecedor", OtherKey="id", IsForeignKey=true)]
		public tipoFornecedor tipoFornecedor
		{
			get
			{
				return this._tipoFornecedor.Entity;
			}
			set
			{
				tipoFornecedor previousValue = this._tipoFornecedor.Entity;
				if (((previousValue != value) 
							|| (this._tipoFornecedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoFornecedor.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoFornecedor.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_fornecedor = value.id;
					}
					else
					{
						this._ID_fornecedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoFornecedor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoMercadoria_Cadproduto", Storage="_tipoMercadoria", ThisKey="ID_tipoMercadoria", OtherKey="id", IsForeignKey=true)]
		public tipoMercadoria tipoMercadoria
		{
			get
			{
				return this._tipoMercadoria.Entity;
			}
			set
			{
				tipoMercadoria previousValue = this._tipoMercadoria.Entity;
				if (((previousValue != value) 
							|| (this._tipoMercadoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoMercadoria.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoMercadoria.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_tipoMercadoria = value.id;
					}
					else
					{
						this._ID_tipoMercadoria = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoMercadoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoProduto_Cadproduto", Storage="_tipoProduto", ThisKey="ID_tipoProduto", OtherKey="id", IsForeignKey=true)]
		public tipoProduto tipoProduto
		{
			get
			{
				return this._tipoProduto.Entity;
			}
			set
			{
				tipoProduto previousValue = this._tipoProduto.Entity;
				if (((previousValue != value) 
							|| (this._tipoProduto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoProduto.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoProduto.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_tipoProduto = value.id;
					}
					else
					{
						this._ID_tipoProduto = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoProduto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoSetor_Cadproduto", Storage="_tipoSetor", ThisKey="ID_sector", OtherKey="id", IsForeignKey=true)]
		public tipoSetor tipoSetor
		{
			get
			{
				return this._tipoSetor.Entity;
			}
			set
			{
				tipoSetor previousValue = this._tipoSetor.Entity;
				if (((previousValue != value) 
							|| (this._tipoSetor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoSetor.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoSetor.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_sector = value.id;
					}
					else
					{
						this._ID_sector = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoSetor");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoUnidadeMedida_Cadproduto", Storage="_tipoUnidadeMedida", ThisKey="ID_unidadeMedida", OtherKey="id", IsForeignKey=true)]
		public tipoUnidadeMedida tipoUnidadeMedida
		{
			get
			{
				return this._tipoUnidadeMedida.Entity;
			}
			set
			{
				tipoUnidadeMedida previousValue = this._tipoUnidadeMedida.Entity;
				if (((previousValue != value) 
							|| (this._tipoUnidadeMedida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipoUnidadeMedida.Entity = null;
						previousValue.Cadproduto.Remove(this);
					}
					this._tipoUnidadeMedida.Entity = value;
					if ((value != null))
					{
						value.Cadproduto.Add(this);
						this._ID_unidadeMedida = value.id;
					}
					else
					{
						this._ID_unidadeMedida = default(Nullable<int>);
					}
					this.SendPropertyChanged("tipoUnidadeMedida");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoFamiliaProduto")]
	public partial class tipoFamiliaProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public tipoFamiliaProduto()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(50)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoFamiliaProduto_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_familiaProduto")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoFamiliaProduto = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoFamiliaProduto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoFornecedor")]
	public partial class tipoFornecedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public tipoFornecedor()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoFornecedor_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_fornecedor")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoFornecedor = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoFornecedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoMercadoria")]
	public partial class tipoMercadoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public tipoMercadoria()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(999) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoMercadoria_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_tipoMercadoria")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoMercadoria = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoMercadoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoProduto")]
	public partial class tipoProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OndescricaoChanging(string value);
    partial void OndescricaoChanged();
    #endregion
		
		public tipoProduto()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descricao", DbType="VarChar(45) NOT NULL", CanBeNull=false)]
		public string descricao
		{
			get
			{
				return this._descricao;
			}
			set
			{
				if ((this._descricao != value))
				{
					this.OndescricaoChanging(value);
					this.SendPropertyChanging();
					this._descricao = value;
					this.SendPropertyChanged("descricao");
					this.OndescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoProduto_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_tipoProduto")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoProduto = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoProduto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoSetor")]
	public partial class tipoSetor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public tipoSetor()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoSetor_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_sector")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoSetor = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoSetor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoUnidadeMedida")]
	public partial class tipoUnidadeMedida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Descricao;
		
		private EntitySet<Cadproduto> _Cadproduto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    #endregion
		
		public tipoUnidadeMedida()
		{
			this._Cadproduto = new EntitySet<Cadproduto>(new Action<Cadproduto>(this.attach_Cadproduto), new Action<Cadproduto>(this.detach_Cadproduto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(20)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoUnidadeMedida_Cadproduto", Storage="_Cadproduto", ThisKey="id", OtherKey="ID_unidadeMedida")]
		public EntitySet<Cadproduto> Cadproduto
		{
			get
			{
				return this._Cadproduto;
			}
			set
			{
				this._Cadproduto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoUnidadeMedida = this;
		}
		
		private void detach_Cadproduto(Cadproduto entity)
		{
			this.SendPropertyChanging();
			entity.tipoUnidadeMedida = null;
		}
	}
}
#pragma warning restore 1591
