//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMercadoEntities : DbContext
    {
        public dbMercadoEntities()
            : base("name=dbMercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TabelaCadProduto1> TabelaCadProduto1Set { get; set; }
        public virtual DbSet<TabelaCadUsuario1> TabelaCadUsuario1Set { get; set; }
        public virtual DbSet<TabelaComprador1> TabelaComprador1Set { get; set; }
        public virtual DbSet<TabelaFamiliaProduto1> TabelaFamiliaProduto1Set { get; set; }
        public virtual DbSet<TabelaFornecedor1> TabelaFornecedor1Set { get; set; }
        public virtual DbSet<TabelaLoja> TabelaLojaSet { get; set; }
        public virtual DbSet<TabelaMercadoria1> TabelaMercadoria1Set { get; set; }
        public virtual DbSet<TabelaSetorProduto1> TabelaSetorProduto1Set { get; set; }
        public virtual DbSet<TabelaSetorUsuario1> TabelaSetorUsuario1Set { get; set; }
        public virtual DbSet<TabelaSituacaoCadastro1> TabelaSituacaoCadastro1Set { get; set; }
        public virtual DbSet<TabelaUnidadeMedida1> TabelaUnidadeMedida1Set { get; set; }
    }
}
