//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMercadoEntities : DbContext
    {
        public dbMercadoEntities()
            : base("name=dbMercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TabelaCadProduto> TabelaCadProdutoes { get; set; }
        public virtual DbSet<TabelaCadUsuario> TabelaCadUsuarios { get; set; }
        public virtual DbSet<TabelaComprador> TabelaCompradors { get; set; }
        public virtual DbSet<TabelaFamiliaProduto> TabelaFamiliaProdutoes { get; set; }
        public virtual DbSet<TabelaFornecedor> TabelaFornecedors { get; set; }
        public virtual DbSet<TabelaLoja> TabelaLojas { get; set; }
        public virtual DbSet<TabelaMercadoria> TabelaMercadorias { get; set; }
        public virtual DbSet<TabelaSetorProduto> TabelaSetorProdutoes { get; set; }
        public virtual DbSet<TabelaSetorUsuario> TabelaSetorUsuarios { get; set; }
        public virtual DbSet<TabelaSituacaoCadastro> TabelaSituacaoCadastroes { get; set; }
        public virtual DbSet<TabelaUnidadeMedida> TabelaUnidadeMedidas { get; set; }
    }
}
