//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaCadUsuario1
    {
        public int id { get; set; }
        public string login { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public Nullable<int> id_tipoSetorUsuario { get; set; }
        public Nullable<int> id_situacaocadastro { get; set; }
        public Nullable<int> id_loja { get; set; }
        public Nullable<System.DateTime> datahoraultimoacesso { get; set; }
    
        public virtual TabelaLoja TabelaLoja { get; set; }
        public virtual TabelaSetorUsuario1 TabelaSetorUsuario { get; set; }
        public virtual TabelaSituacaoCadastro1 TabelaSituacaoCadastro { get; set; }
    }
}
