//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaCadProduto1
    {
        public int id { get; set; }
        public string codigoBarra { get; set; }
        public string descricaoCompleta { get; set; }
        public Nullable<int> qtdEmbalagem { get; set; }
        public Nullable<int> ID_unidadeMedida { get; set; }
        public Nullable<int> ID_sectorProduto { get; set; }
        public Nullable<decimal> custoFinal { get; set; }
        public Nullable<decimal> custoVenda { get; set; }
        public Nullable<int> ID_familiaProduto { get; set; }
        public string descricaoNota { get; set; }
        public Nullable<decimal> pesoLiquido { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<System.DateTime> validade { get; set; }
        public Nullable<decimal> pesoBruto { get; set; }
        public Nullable<int> larguraEmbalagem { get; set; }
        public Nullable<int> alturaEmbalagem { get; set; }
        public Nullable<decimal> margemLucro { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public Nullable<int> ID_tipoMercadoria { get; set; }
        public Nullable<bool> aceitaMultiplicacaoPdv { get; set; }
        public Nullable<int> ID_fornecedor { get; set; }
        public Nullable<int> diasDeVendas { get; set; }
        public Nullable<bool> pesavel { get; set; }
        public Nullable<bool> vendaControlada { get; set; }
        public Nullable<int> ID_Comprador { get; set; }
        public Nullable<bool> vendaPdv { get; set; }
        public Nullable<decimal> estoque { get; set; }
        public Nullable<bool> abaixoMinimo { get; set; }
        public Nullable<int> quantEmbalagem { get; set; }
        public Nullable<int> ID_Loja { get; set; }
        public Nullable<bool> cotacao { get; set; }
        public Nullable<bool> permiteDesconto { get; set; }
    
        public virtual TabelaFamiliaProduto1 TabelaFamiliaProduto { get; set; }
        public virtual TabelaMercadoria1 TabelaMercadoria { get; set; }
        public virtual TabelaSetorProduto1 TabelaSetorProduto { get; set; }
        public virtual TabelaUnidadeMedida1 TabelaUnidadeMedida { get; set; }
        public virtual TabelaComprador1 TabelaComprador { get; set; }
        public virtual TabelaFornecedor1 TabelaFornecedor { get; set; }
        public virtual TabelaLoja TabelaLoja { get; set; }
    }
}
